stages:
  data_ingestion:
    cmd: python src/data/data_ingestion.py
    deps:
      - src/data/data_ingestion.py
    params:
      - data_ingestion.test_size
    outs:
      - artifacts/data
  
  data_preprocessing:
    cmd: python src/data/data_preprocessing.py
    deps:
      - src/data/data_preprocessing.py
      - artifacts/data/train.csv
      - artifacts/data/test.csv
    outs:
      - artifacts/interim

  model_building:
    cmd: python src/model/model_building.py
    deps:
      - src/model/model_building.py
      - artifacts/interim/train_processed.csv
    params:
      - model_building.ngram_range
      - model_building.max_features
      - model_building.learning_rate
      - model_building.max_depth
      - model_building.n_estimators
    outs:
      - artifacts/models
      - artifacts/models
  
  model_evaluation:
    cmd: python src/model/model_evaluation.py
    deps:
      - src/model/model_evaluation.py
      - artifacts/models/lgbm_model.pkl
      - artifacts/models/tfidf_vectorizer.pkl
      - artifacts/interim/test_processed.csv
      - artifacts/interim/train_processed.csv


  model_registration:
    cmd: python src/model/register_model.py
    deps:
      - src/model/register_model.py
      - artifacts/models/lgbm_model.pkl
      - artifacts/models/tfidf_vectorizer.pkl
      - experiment_info.json
      - artifacts/interim/test_processed.csv
    outs:
      - model_registration_info.json
      